[package]
name = "tazui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taz = {git = "https://github.com/BaGoA/Taz", branch = "main"}
ncurses = "5.101.0"
